alias: Meshcore - Maintenance Do Action
description: With Selected Contact Requested Action is Done
triggers: []
conditions: []
actions:
  - variables:
      id: "{{ states('input_select.meshcore_selection') | string }}"
      public_key: "{{ id[-20:-8] }}"
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.meshcore_maintenance_focus
            state: ADD DISCOVERED
        sequence:
          - action: meshcore.execute_command
            data:
              command: add_contact {{ public_key }}
      - conditions:
          - condition: state
            entity_id: input_select.meshcore_maintenance_focus
            state: REMOVE CONTACT
        sequence:
          - action: meshcore.execute_command
            data:
              command: remove_contact {{ public_key }}
      - conditions:
          - condition: state
            entity_id: input_select.meshcore_maintenance_focus
            state: TOGGLE FAVORITE
        sequence:
          - variables:
              favorite: >-
                {{
                state_attr(states('input_select.meshcore_selection'),'flags')}}
              toggle: |-
                {% if favorite == 0 %}
                  1
                {% else %}
                  0
                {% endif %}
          - action: meshcore.execute_command
            data:
              command: change_contact_flags {{ public_key }} {{ toggle }}
            enabled: true
      - conditions:
          - condition: state
            entity_id: input_select.meshcore_maintenance_focus
            state: REMOVE DISCOVERED
        sequence:
          - action: conversation.process
            metadata: {}
            data:
              text: Sorry, Work in Progress
  - stop: Created by WJ4IoT
    enabled: false
mode: single
